import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Pet Store',
  description: 'Generated by Ekramy',
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="text-sm text-zinc-900 min-h-screen">{children}</div>;
}
